### PR TITLE
Use treesitter for folding

### PR DESCRIPTION
**Pull request by phozzy**

### CODE REVIEW

**Comment by Bluesboy** [comment]
Could you please, move this to `config/nvim/lua/user/options.lua`?

**Review by Bluesboy — CHANGES_REQUESTED** [review]
Move options to options.lua please

**Comment by phozzy** [comment]
The thing is that these changes highly depend on this extension. But if you think that it's better to have them there, I can do that.

**Comment by Bluesboy** [comment]
Makes sense, merging.

**Pull request merged**
